apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
    name: build-neurologia-image
    spec:
        params:
              - name: IMAGE
                    type: string
                      resources:
                            inputs:
                                    - name: source
                                            type: git
                                              steps:
                                                    - name: build
                                                          image: gcr.io/kaniko-project/executor:latest
                                                                args:
                                                                          - "--dockerfile=/workspace/source/Dockerfile"
                                                                                  - "--context=/workspace/source"
                                                                                          - "--destination=$(params.IMAGE)"

